version: '3'
services:
  app:
    command: 'go run main.go'
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ".:/app"
    tty: true
    stdin_open: true
    env_file:
      - .env
    environment:
      MYSQL_DB_HOST: db
  db:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sqls/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    restart: always
    env_file:
      - .env
volumes:
  mysql_data: